pipeline {
    agent {
        dockerfile { dir 'chrome-extension' }
    }
    options {
        timeout(time: 10)
    }
    stages {
        stage('Install') {
            steps {
                sh 'echo 2'
            }
        }
    }
}