pipeline {
    agent {
        dockerfile { dir 'chrome-extension' }
    }
    options {
        timeout(time: 10)
    }
    stages {
        stage('Install') {
            steps {
                script {
                    def response = httpRequest "http://nexus.crinfra.net:8081/nexus/service/rest/beta/search?name=vcd-amazon-alexa-skill"

                    def json = readJSON text: response.getContent()

                    def params = json.items.collect { it.version }.sort().join("\n")

                    env.VERSION = input(
                        message: "Enter version",
                        ok: "Publish",
                        parameters: [ [$class: 'ChoiceParameterDefinition', choices: params, description: 'Properties', name: 'prop'] ]
                    )
                }
                sh 'echo $VERSION'
            }
        }
    }
}
