import java.io.BufferedReader
import java.io.InputStreamReader
import java.net.URL
import groovy.json.JsonSlurper

pipeline {
    agent {
        dockerfile { dir 'chrome-extension' }
    }
    options {
        timeout(time: 10)
    }
    stages {
        stage('Install') {
            steps {
                script {

                    def choices = []
                    def url = new URL("http://nexus.crinfra.net:8081/nexus/service/rest/beta/search?name=vcd-amazon-alexa-skill")
                    def conn = url.openConnection()
                    conn.setDoOutput(true)

                    def reader = new BufferedReader(new InputStreamReader(conn.getInputStream()))
                    def results = new JsonSlurper().parseText(reader.getText());
                    reader.close()

                    results.items.each { data -> choices.push(data.version) }
                    choices.sort()

                    env.VERSION = input(
                        message: "Enter version",
                        ok: "Publish",
                        parameters: [ [$class: 'ChoiceParameterDefinition', choices: choices.sort(), description: 'Properties', name: 'prop'] ]
                    )
                }
                sh 'echo $VERSION'
            }
        }
    }
}