pipeline {
    agent {
        docker 'appropriate/curl'
    }
    options {
      timeout(time: 10)
    }
    stages {
//        stage('Install') {
//            steps {
//                sh 'yarn'
//            }
//        }
//        stage('Build') {
//            steps {
//                sh 'yarn build'
//            }
//        }
//        stage('Test') {
//            steps {
//                sh 'yarn lint'
//                sh 'yarn test'
//            }
//        }
        stage('Publish dev') {
            environment {
//                NPMRC = credentials('cr-nexus-npmrc')
                NPMRC = credentials('NPMRC')
//                BITBUCKET = credentials('jenkins_bitbucket')
                BITBUCKET = credentials('bitbucket-admin')
            }
            when {
                allOf {
                    environment name: 'CHANGE_ID', value: ''
                    branch 'master'
                }
            }
            steps {
                script {
                    withCredentials([string(credentialsId: "CHROME_STORE_PARAMS", variable: 'CHROME_STORE')]) {
                        sh 'echo $CHROME_STORE'
                    }
                }
//                sh 'echo -e $NPMRC > .npmrc'
//                sh 'npm --no-git-tag-version version prerelease'
//                sh 'npm publish'
//                sh 'git -c "user.name=Jenkins" -c "user.email=Jenkins" commit --no-verify -m "Jenkins version bump" package.json'
//                sh 'git push https://${BITBUCKET_USR}:${BITBUCKET_PSW}@stash.consumer.org/scm/cro/global-navigation-ui.git HEAD:$BRANCH_NAME'
            }
        }
//        stage('Publish release') {
//            environment {
//                NPMRC = credentials('cr-nexus-npmrc')
//                BITBUCKET = credentials('jenkins_bitbucket')
//            }
//            when {
//                allOf {
//                    environment name: 'CHANGE_ID', value: ''
//                    branch 'master'
//                }
//            }
//            steps {
//                script {
//                    env.VERSION = input(
//                        message: "Enter version",
//                        ok: "Publish",
//                        parameters: [
//                            string(name: 'VERSION', defaultValue: '', description: 'Version to publish')
//                        ]
//                    )
//                }
//                sh 'echo -e $NPMRC > .npmrc'
//                sh 'git config user.name Jenkins'
//                sh 'git config user.email Jenkins'
//                sh 'npm version $VERSION'
//                sh 'npm publish'
//                sh 'git push https://${BITBUCKET_USR}:${BITBUCKET_PSW}@stash.consumer.org/scm/cro/global-navigation-ui.git HEAD:$BRANCH_NAME --tags'
//            }
//        }
    }
    post {
        always {
            deleteDir()
        }
    }
}