pipeline {
    agent {
        dockerfile { dir 'chrome-extension' }
    }
    options {
      timeout(time: 10)
    }
    stages {
//        stage('Install') {
//            steps {
//                sh 'yarn'
//            }
//        }
//        stage('Build') {
//            steps {
//                sh 'yarn build'
//            }
//        }
//        stage('Test') {
//            steps {
//                sh 'yarn lint'
//                sh 'yarn test'
//            }
//        }
        stage('Publish dev') {
            environment {
//                NPMRC = credentials('cr-nexus-npmrc')
                NPMRC = credentials('NPMRC')
//                BITBUCKET = credentials('jenkins_bitbucket')
                BITBUCKET = credentials('bitbucket-admin')
                CHROME_STORE = credentials('CHROME_STORE_PARAMS')
                APP_ID = 'hhenonbofkdabjeiofocpfapcadiknoe'
            }
            when {
                allOf {
                    environment name: 'CHANGE_ID', value: ''
                    branch 'master'
                }
            }
            steps {
                sh 'echo -e $NPMRC > .npmrc'
                sh 'cd chrome-extension/extension/;zip -r ../ext.zip .;'
                sh '''#!/bin/ash
                    cd chrome-extension
                    ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "$CHROME_STORE&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
                    curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T ext.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
                    curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -H "publishTarget: trustedTesters" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
                '''
//                sh 'npm --no-git-tag-version version prerelease'
//                sh 'npm publish'
//                sh 'git -c "user.name=Jenkins" -c "user.email=Jenkins" commit --no-verify -m "Jenkins version bump" package.json'
//                sh 'git push https://${BITBUCKET_USR}:${BITBUCKET_PSW}@stash.consumer.org/scm/cro/global-navigation-ui.git HEAD:$BRANCH_NAME'
            }
        }
//        stage('Publish release') {
//            environment {
//                NPMRC = credentials('cr-nexus-npmrc')
//                BITBUCKET = credentials('jenkins_bitbucket')
//            }
//            when {
//                allOf {
//                    environment name: 'CHANGE_ID', value: ''
//                    branch 'master'
//                }
//            }
//            steps {
//                script {
//                    env.VERSION = input(
//                        message: "Enter version",
//                        ok: "Publish",
//                        parameters: [
//                            string(name: 'VERSION', defaultValue: '', description: 'Version to publish')
//                        ]
//                    )
//                }
//                sh 'echo -e $NPMRC > .npmrc'
//                sh 'git config user.name Jenkins'
//                sh 'git config user.email Jenkins'
//                sh 'npm version $VERSION'
//                sh 'npm publish'
//                sh 'git push https://${BITBUCKET_USR}:${BITBUCKET_PSW}@stash.consumer.org/scm/cro/global-navigation-ui.git HEAD:$BRANCH_NAME --tags'
//            }
//        }
    }
    post {
        always {
            deleteDir()
        }
    }
}